### ISSUE TITLE
Access UnicodeCNN model for inference

### ISSUE THREAD

**Issue by AADeLucia** [mikeizbicki/geolocation-python#1]
I am working on a twitter geolocation project and came across your paper "Geolocating Tweets in any Language at any Location", and am interested in accessing your UnicodeCNN model, and if possible, your data. My use case is to use your model as a comparison on my own Twitter geolocation dataset (inference only).

Any assistance you can provide is greatly appreciated. 

Thanks,
Alexandra

**Comment by AADeLucia** [comment]
@mikeizbicki ?

**Comment by mikeizbicki** [comment]
Unfortunately, I don't have the trained model weights anymore, so I don't think it'll be realistically possible to make the comparison.  They were accidentally deleted when I changed jobs a while back :(

**Comment by AADeLucia** [comment]
Ah, thank you for your update.
